# Site Information
site_name: Abdellah LAASSAIRI
site_description: Personal blog and portfolio
site_url: https://abdellah-laassairi.github.io/blog/
site_author: Abdellah LAASSAIRI
repo_url: https://github.com/Abdellah-Laassairi/blog
repo_name: Abdellah-Laassairi/blog

# Navigation
nav:
  - Home: index.md
  - Blog: blog/index.md
  - About: about.md

# Theme Configuration
theme:
  name: terminal
  palette: gruvbox_dark
  font:
    text: Roboto
    code: Roboto Mono
  custom_dir: docs/overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

# Markdown Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - tables

# Plugins
plugins:
  - pub-blog
  - pub-social
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en

extra_css:
  - terminal/terminal.css
  - https://cdn.jsdelivr.net/npm/xterm@5.1.0/css/xterm.min.css

extra_javascript:
  # External dependencies
  - https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.1.0/js-yaml.min.js
  - https://cdn.jsdelivr.net/npm/xterm@5.1.0/lib/xterm.min.js
  - https://cdn.jsdelivr.net/npm/xterm-addon-fit@0.7.0/lib/xterm-addon-fit.min.js
  - https://cdn.jsdelivr.net/npm/xterm-addon-web-links@0.8.0/lib/xterm-addon-web-links.min.js
  - https://cdn.jsdelivr.net/npm/xterm-addon-search@0.11.0/lib/xterm-addon-search.min.js

  # Main terminal initialization
  - terminal/terminal.js

  # Terminal core and configuration
  - terminal/config/terminal-config.js
  - terminal/config/chat-config.js

  # Terminal utilities and services
  - terminal/utils/TextBuffer.js
  - terminal/data/fileSystem.js
  - terminal/services/ChatService.js
  - terminal/services/CommandProcessor.js
