# Site Information
site_name: Abdellah LAASSAIRI
site_description: Personal blog and portfolio
site_url: https://abdellah-laassairi.github.io/blog/
site_author: Abdellah LAASSAIRI
repo_url: https://github.com/Abdellah-Laassairi/blog
repo_name: Abdellah-Laassairi/blog

# Navigation
nav:
  - Home: index.md
  - Blog: blog/index.md
  # - Projects: projects.md
  # - About: about.md
  # - Contact: contact.md

# Theme Configuration
theme:
  name: terminal
  palette: gruvbox_dark
  font:
    text: Roboto
    code: Roboto Mono
  custom_dir: docs/overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

# Markdown Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - tables

# Plugins
plugins:
  - termynal:
      title: bash
      buttons: macos
      prompt_literal_start:
        - "$"
        - ">"

  - search:
      separator: '[\s\-\.]+'
      lang:
        - en
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.0/highlight.min.js
  - https://unpkg.com/highlightjs-cobol/dist/cobol.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/xterm/5.5.0/xterm.js

  - https://cdn.jsdelivr.net/npm/xterm-addon-fit@0.7.0/lib/xterm-addon-fit.js
  - https://cdn.jsdelivr.net/npm/xterm-addon-web-links@0.8.0/lib/xterm-addon-web-links.js
  - https://cdn.jsdelivr.net/npm/xterm-addon-search@0.11.0/lib/xterm-addon-search.js

  - overrides/terminal.js
  - overrides/highlight.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.0/styles/a11y-dark.min.css # Dark mode style
  - https://cdnjs.cloudflare.com/ajax/libs/xterm/5.5.0/xterm.css # Dark mode style
  - overrides/terminal.css
