prompt_colors:
  env: "\x1b[1;32m"      # Bold green for (base)
  user: "\x1b[1;32m"     # Bold green for username
  at: "\x1b[0m"          # Default color for @
  host: "\x1b[1;32m"     # Bold green for hostname
  path: "\x1b[1;34m"     # Bold blue for directory
  symbol: "\x1b[0m"      # Default color for $

chat_prompt: "\x1b[1;34m🤖 >\x1b[0m " # Bold blue chat prompt

terminal_options:
  fontFamily: '"Fira Code", "Source Code Pro", "Consolas", monospace'
  fontSize: 14
  lineHeight: 1.2
  theme:
    background: "#1e1e1e"
    foreground: "#f0f0f0"
    cursor: "#f0f0f0"
    selection: "rgba(255, 255, 255, 0.3)"
    black: "#000000"
    red: "#e06c75"
    green: "#98c379"
    yellow: "#d19a66"
    blue: "#61afef"
    magenta: "#c678dd"
    cyan: "#56b6c2"
    white: "#abb2bf"
    brightBlack: "#5c6370"
    brightRed: "#e06c75"
    brightGreen: "#98c379"
    brightYellow: "#d19a66"
    brightBlue: "#61afef"
    brightMagenta: "#c678dd"
    brightCyan: "#56b6c2"
    brightWhite: "#ffffff"
  cursorBlink: true
  cursorStyle: "block"
  scrollback: 5000
  smoothScrollDuration: 0
  scrollSensitivity: 40
  macOptionIsMeta: true
  fastScrollModifier: "alt"
  fastScrollSensitivity: 60
  minimumContrastRatio: 4.5
  allowTransparency: false
  letterSpacing: 0
  padding: 8
